### ISSUE TITLE
Binary releases

### ISSUE THREAD

**Issue by jcgruenhage** [famedly/acmed-hook-ssh#2]
We need binary releases so that we can deploy the binaries for the receiving end onto the target hosts, which should be built in the CI and attached to a GitHub Release when pushing a tag. We also need binary releases for a few other tools, like https://github.com/famedly/hookd, so we should likely build a proper workflow for this in https://github.com/famedly/github-workflows

**Comment by CherryKitten** [comment]
We have https://github.com/famedly/github-workflows/blob/main/.github/workflows/rust.yml now, we just need to add a workflow call for this repo

Edit: Depends on https://github.com/famedly/github-workflows/issues/28 being done first
